export const timer = [
  {
    name: "First Section",
    fields: [
      // {
      //   code: "showEvidence",
      //   dataType: "text",
      //   description: "Allow Evidence",
      //   editable: true,
      //   index: 5,
      //   inputType: "radio",
      //   label: "Allow Evidence",
      //   name: "showEvidence",
      //   placeholder: "showEvidence",
      //   renderingHints: {
      //     class: "sb-g-col-lg-1",
      //   },
      //   range: ["Yes", "No"],
      //   required: true,
      //   visible: true,
      // },
      // {
      //   code: "evidenceMimeType",
      //   dataType: "list",
      //   depends: ["showEvidence"],
      //   description: "Evidence",
      //   editable: true,
      //   inputType: "multiselect",
      //   label: "evidence",
      //   name: "evidenceMimeType",
      //   placeholder: "evidence",
      //   renderingHints: {
      //     class: "sb-g-col-lg-1",
      //   },
      //   required: false,
      //   visible: true,
      //   range: [
      //     {
      //       value: "image/png",
      //       label: "image/png",
      //     },
      //     { value: "audio/mp3", label: "audio/mp3" },
      //     { value: "video/mp4", label: "video/mp4" },
      //     { value: "video/webm", label: "video/webm" },
      //   ],
      // },
      {
        code: "allowTcM",
        name: "allowTcM",
        label: "Add Evidence collection methods",
        placeholder: "Add Evidence collection methods",
        description: "Add Evidence collection methods",
        dataType: "text",
        inputType: "checkbox",
        editable: true,
        required: false,
        visible: true,
        renderingHints: {
          class: "sb-g-col-lg-1",
        },
      },
      {
        code: "recordedBy",
        name: "RecordedBy",
        label: "Observation Recorded By",
        placeholder: "Select Observation Recorded By",
        description: "Select Observation Recorded By",
        dataType: "text",
        inputType: "select",
        editable: true,
        output: "label",
        required: true,
        visible: true,
        renderingHints: {
          class: "sb-g-col-lg-1 required",
        },
        range: [
          {
            value: "Self",
            label: "Self",
          },
          {
            value: "External",
            label: "External",
          },
        ],
        validations: [
          {
            type: "required",
            message: "Observation Recorded By is required",
          },
        ],
      },
      {
        code: "allowECM",
        name: "allowECM",
        depends: ["recordedBy"],
        label: "Add Evidence collection methods",
        placeholder: "Add Evidence collection methods",
        description: "Add Evidence collection methods",
        dataType: "text",
        inputType: "checkbox",
        editable: true,
        required: false,
        visible: true,
        renderingHints: {
          class: "sb-g-col-lg-1",
        },
      },
      {
        code: "ecm",
        name: "ECM",
        depends: ["allowECM"],
        label: "Select ECM's",
        placeholder: "Select ECM's",
        description: "ECM for the Observation with rubrics",
        dataType: "list",
        inputType: "selectTextBox",
        editable: true,
        required: false,
        visible: true,
        renderingHints: {
          class: "sb-g-col-lg-1",
        },
        options: [
          "Student interview",
          "Teacher interview",
          "School walk",
          "Head teacher interview",
        ],
      },
    ],
  },
];
